name: "gender_pay_gap"
employee_generator:
  _target_: ticket_generation.src.employee_generator.EmployeeGenderPayGapGenerator
df_provider:
  _target_: ticket_generation.src.df_provider.GenderPayGapDfProvider
  number_of_data: -1 # number of data to sample from original dataset (-1 means get all data)
  shuffle: True # boolean to shuffle or not the data before sampling
  file_name: "uk_gender_pay_gap_2020_2021.csv" # file name of the dataset
  columns: ["DiffMeanHourlyPercent"] # columns name in the csv
text_generator:
  _target_: ticket_generation.src.text_generator.TicketGenderPayGapTextGenerator
  file_name: "templates.json" # file name of the template json file
  category: "Salary" # Must correspond to the keys in the templates.json file
  sub_category: "Gender pay gap" # Must correspond to the keys in the templates.json file
