name: "info_accommodation"
employee_generator:
  _target_: ticket_generation.src.employee_generator.EmployeeInfoAccommodationGenerator
df_provider:
  _target_: ticket_generation.src.df_provider.InfoAccommodationDfProvider
  number_of_data: -1 # number of data to sample from original dataset (-1 means get all data)
  shuffle: True # boolean to shuffle or not the data before sampling
  file_name: "geonames-all-cities-with-a-population-over-100000.csv" # file name of the dataset
  columns: ["ASCII Name", "Country Code", "Country name EN"] # columns name in the csv
text_generator:
  _target_: ticket_generation.src.text_generator.TicketInfoAccommodationTextGenerator
  file_name: "templates.json" # file name of the template json file
  category: "Ask information" # Must correspond to the keys in the templates.json file
  sub_category: "Accommodation" # Must correspond to the keys in the templates.json file
