name: "salary"
employee_generator:
  _target_: ticket_generation.src.employee_generator.EmployeeSalaryGenerator
df_provider:
  _target_: ticket_generation.src.df_provider.SalaryDfProvider
  number_of_data: -1 # number of data to sample from original dataset (-1 means get all data)
  shuffle: True # boolean to shuffle or not the data before sampling
  file_name: "national_M2021_dl_processed.csv" # file name of the dataset
  columns: ["OCC_TITLE", "TOT_EMP", "A_MEAN", "MEAN_PRSE"] # columns name in the csv
text_generator:
  _target_: ticket_generation.src.text_generator.TicketSalaryTextGenerator
  file_name: "templates.json" # file name of the template json file
  category: "Salary" # Must correspond to the keys in the templates.json file
  sub_category: "Salary raise" # Must correspond to the keys in the templates.json file
