repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0 # Use the ref you want to point at
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=10000"]
      - id: check-yaml
      - id: trailing-whitespace
  - repo: https://github.com/PyCQA/autoflake
    rev: v1.5.3
    hooks:
      - id: autoflake
        args:
          - --remove-all-unused-imports
          - --remove-unused-variables
          - --ignore-init-module-imports
          - --in-place
  - repo: https://github.com/pycqa/isort
    rev: 5.6.4
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files", "--line-length=120"]
  - repo: https://github.com/ambv/black
    rev: 22.6.0
    hooks:
      - id: black
        types: [python]
        args:
          - --line-length=119
          - --include='\.pyi?$'
          - --exclude="""\.git |
            \.__pycache__|
            \.mypy_cache|
            \.venv|
            \.linux_venv|
            \.outputs|
            \.multirun|
            \.results|"""
  - repo: https://github.com/pre-commit/mirrors-pylint
    rev: v3.0.0a3
    hooks:
      - id: pylint
        args: [--disable=all, --enable=unused-import]
